Repository AssassinBro/SS, pull requests merged in 2025-05, with the labels that each got.

#11 Если я не закончу работать над эрорами до 22 47, мама меня лицом по клавлпартовыащжоатиыщвоцфыитрваэзыфощшщжаруцоыжтлаоиы мбтв
  Resources/Prototypes/Roles/Jobs/Command/captain.yml
Labels: Changes: Localization, S: Untriaged, Changes: No C#, size/XS

#13 fix(jobs)
  Resources/Prototypes/Roles/Jobs/Civilian/clown.yml
  Resources/Prototypes/Roles/Jobs/Engineering/technical_assistant.yml
  Resources/Prototypes/Roles/Jobs/Medical/medical_intern.yml
Labels: S: Untriaged, Changes: No C#, size/S

#14 fix
  Resources/Audio/Backmen/Voice/Reptilian/attributions.yml
  Resources/Audio/Backmen/Voice/Reptilian/reptilian_hiss.ogg
  Resources/Locale/ru-RU/backmen/actions/types.ftl
  Resources/Prototypes/SoundCollections/disease.yml
  Resources/Prototypes/_Backmen/Actions/types.yml
  Resources/Prototypes/_Backmen/Diseases/furry_virus.yml
  Resources/Prototypes/_Backmen/SoundCollections/emotions.yml
  Resources/Prototypes/_Backmen/Voice/speech_emote_sounds.yml
  Resources/Prototypes/_Backmen/Voice/speech_emotes.yml
  Resources/Textures/Backmen/Icons/verbiconfangs.png
  Resources/Textures/Backmen/Interface/Emotes/hiss.png
Labels: Changes: Localization, S: Untriaged, size/M, Changes: No C#, Changes: Audio
